#!/bin/bash

# Script to run the complete rating update workflow
# This script orchestrates the entire process of updating player ratings:
# 1. Generate sample match data (if needed)
# 2. Run the Python rating calculation
# 3. Import the results into the database

set -e  # Exit on any error

echo "Starting complete rating update workflow..."

# Navigate to the project root directory
cd "$(dirname "$0")"

# Check if required files exist
if [ ! -f "pool_elo.py" ]; then
  echo "Error: pool_elo.py not found in project root"
  exit 1
fi

# Generate sample match data if it doesn't exist
if [ ! -f "eloq-webapp/data/matches.csv" ]; then
  echo "Generating sample match data..."
  cd eloq-webapp
  npx tsx scripts/generate-matches-data.ts
  cd ..
fi

# Check if matches file exists now
if [ ! -f "eloq-webapp/data/matches.csv" ]; then
  echo "Error: matches.csv not found in eloq-webapp/data/"
  exit 1
fi

# Run Python rating calculation
echo "Running Python rating calculation..."
python3 pool_elo.py --matches eloq-webapp/data/matches.csv

# Check if the Python script generated the expected output files
if [ ! -f "eloq-webapp/data/pool_final_ratings.csv" ]; then
  echo "Error: pool_final_ratings.csv not generated by Python script"
  exit 1
fi

echo "Python rating calculation completed successfully"

# Import results to database
echo "Importing ratings to database..."
cd eloq-webapp
npx tsx scripts/import-ratings.ts

echo "Complete rating update workflow finished!"