#!/bin/bash

# Script to update player ratings by running the Python rating system and importing results
# This script automates the entire rating update workflow

set -e  # Exit on any error

echo "Starting rating update process..."

# Navigate to the project root directory
cd "$(dirname "$0")"

# Check if required files exist
if [ ! -f "pool_elo.py" ]; then
  echo "Error: pool_elo.py not found in project root"
  exit 1
fi

if [ ! -f "eloq-webapp/data/matches.csv" ]; then
  echo "Error: matches.csv not found in eloq-webapp/data/"
  exit 1
fi

# Run Python rating calculation
echo "Running Python rating calculation..."
python3 pool_elo.py --matches eloq-webapp/data/matches.csv

# Check if the Python script generated the expected output files
if [ ! -f "eloq-webapp/data/pool_final_ratings.csv" ]; then
  echo "Error: pool_final_ratings.csv not generated by Python script"
  exit 1
fi

echo "Python rating calculation completed successfully"

# Import results to database
echo "Importing ratings to database..."
cd eloq-webapp
npx tsx scripts/import-ratings.ts

echo "Rating update process completed!"