// Script to generate final ratings CSV from Python script output
// This script reads the pool_final_ratings.csv file generated by pool_elo.py and creates a properly formatted version

import * as fs from 'fs';
import * as path from 'path';
import { parse } from 'csv-parse';

interface PythonRatingRow {
  player: string;
  rating: string;
  matches: string;
}

interface FinalRatingRow {
  player: string;
  rating: number;
  matches: number;
}

/**
 * Generate final ratings CSV from Python output
 * @param inputFile Path to the pool_final_ratings.csv file generated by pool_elo.py
 * @param outputFile Path to the output file
 */
async function generateFinalRatings(inputFile: string, outputFile: string): Promise<void> {
  try {
    // Check if input file exists
    if (!fs.existsSync(inputFile)) {
      throw new Error(`Input file ${inputFile} not found`);
    }

    // Read and parse the input CSV file
    const csvData = fs.readFileSync(inputFile, 'utf8');
    const records: PythonRatingRow[] = await new Promise((resolve, reject) => {
      parse(csvData, {
        columns: true,
        skip_empty_lines: true,
        trim: true
      }, (err, output) => {
        if (err) reject(err);
        else resolve(output as PythonRatingRow[]);
      });
    });

    console.log(`Parsed ${records.length} players from Python output`);

    // Convert to final rating format
    const finalRatings: FinalRatingRow[] = records.map(record => ({
      player: record.player,
      rating: parseFloat(record.rating),
      matches: parseInt(record.matches, 10)
    }));

    // Sort by rating (descending) to determine rankings
    finalRatings.sort((a, b) => b.rating - a.rating);

    // Generate CSV content
    let csvContent = 'player,rating,matches\n';
    finalRatings.forEach((rating, index) => {
      csvContent += `"${rating.player}",${rating.rating.toFixed(2)},${rating.matches}\n`;
    });

    // Write to output file
    fs.writeFileSync(outputFile, csvContent);
    console.log(`Generated final ratings CSV with ${finalRatings.length} players and saved to ${outputFile}`);
  } catch (error) {
    console.error('Error generating final ratings:', error);
    throw error;
  }
}

// Main function
async function main() {
  try {
    // Define file paths
    const inputFile = path.join(__dirname, '..', 'data', 'pool_final_ratings.csv');
    const outputFile = path.join(__dirname, '..', 'data', 'final_ratings.csv');
    
    // Generate final ratings
    await generateFinalRatings(inputFile, outputFile);
    
    console.log('Final ratings generation completed successfully');
  } catch (error) {
    console.error('Error in final ratings generation:', error);
    process.exit(1);
  }
}

// Run the script if called directly
if (require.main === module) {
  main();
}

export default generateFinalRatings;