#!/usr/bin/env tsx

// Script to import Python-generated ratings into the database
// This script reads the pool_final_ratings.csv file and updates player ratings in the database

import * as fs from 'fs';
import * as path from 'path';
import { parse } from 'csv-parse';
import { query } from '../src/lib/db';

interface PythonRatingRow {
  player: string;
  rating: string;
  matches: string;
}

async function importRatings() {
  try {
    console.log('Importing ratings from Python-generated CSV...');
    
    // Initialize database connection
    const { initializeDataConnection } = await import('../src/lib/data-connection');
    await initializeDataConnection();
    
    // Path to the CSV file generated by pool_elo.py
    const csvFilePath = path.join(__dirname, '..', 'data', 'pool_final_ratings.csv');
    
    // Check if CSV file exists
    if (!fs.existsSync(csvFilePath)) {
      throw new Error(`CSV file not found: ${csvFilePath}`);
    }
    
    // Read and parse CSV file
    const csvData = fs.readFileSync(csvFilePath, 'utf8');
    const records: PythonRatingRow[] = await new Promise((resolve, reject) => {
      parse(csvData, {
        columns: true,
        skip_empty_lines: true,
        trim: true
      }, (err, output) => {
        if (err) reject(err);
        else resolve(output as PythonRatingRow[]);
      });
    });
    
    console.log(`Parsed ${records.length} player ratings from CSV`);
    
    // Update player ratings in database
    let updatedCount = 0;
    let importedCount = 0;
    
    for (const record of records) {
      try {
        // Check if player exists in database
        const playerResult = await query(
          'SELECT id FROM players WHERE name = $1',
          [record.player]
        );
        
        if (playerResult.rows.length > 0) {
          // Update existing player
          const playerId = playerResult.rows[0].id;
          await query(
            `UPDATE players SET 
              rating = $1, 
              matches_played = $2,
              provisional = CASE WHEN $2 < 30 THEN true ELSE false END,
              last_played = CURRENT_TIMESTAMP
            WHERE id = $3`,
            [
              parseFloat(record.rating),
              parseInt(record.matches, 10),
              playerId
            ]
          );
          updatedCount++;
          console.log(`Updated rating for player ${record.player} (${playerId}): ${record.rating}`);
        } else {
          // Create new player
          const playerId = `player-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
          await query(
            `INSERT INTO players (
              id, name, rating, matches_played, provisional, 
              wins, losses, win_rate, ranking, join_date, last_played
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
            [
              playerId,
              record.player,
              parseFloat(record.rating),
              parseInt(record.matches, 10),
              parseInt(record.matches, 10) < 30, // provisional if < 30 matches
              0, // wins (will be calculated from matches)
              0, // losses (will be calculated from matches)
              0.0, // win_rate (will be calculated from matches)
              0, // ranking (will be calculated later)
              new Date(), // join_date
              new Date() // last_played
            ]
          );
          importedCount++;
          console.log(`Created new player ${record.player} (${playerId}) with rating: ${record.rating}`);
        }
      } catch (error) {
        console.error(`Error processing player ${record.player}:`, error);
        // Continue with other players even if one fails
      }
    }
    
    // Update player rankings based on new ratings
    await updatePlayerRankings();
    
    console.log(`Rating import completed: ${importedCount} new players, ${updatedCount} updated players`);
  } catch (error) {
    console.error('Error importing ratings:', error);
    process.exit(1);
  }
}

async function updatePlayerRankings() {
  try {
    // Get all players ordered by rating (descending)
    const playersResult = await query(
      'SELECT id, rating FROM players ORDER BY rating DESC'
    );
    
    // Update each player's ranking
    for (let i = 0; i < playersResult.rows.length; i++) {
      const player = playersResult.rows[i];
      const ranking = i + 1;
      
      await query(
        'UPDATE players SET ranking = $1 WHERE id = $2',
        [ranking, player.id]
      );
    }
    
    console.log(`Updated rankings for ${playersResult.rows.length} players`);
  } catch (error) {
    console.error('Error updating player rankings:', error);
    throw error;
  }
}

// Run the script if called directly
if (require.main === module) {
  importRatings();
}

export default importRatings;