// Script to initialize the database with Python-generated player data
// This script reads the pool_final_ratings.csv file and initializes the database with player ratings

import * as fs from 'fs';
import * as path from 'path';
import { parse } from 'csv-parse';
import { query } from '../src/lib/db';
import { createTables } from '../src/lib/db/init';

interface PythonRatingRow {
  player: string;
  rating: string;
  matches: string;
}

async function initDatabaseWithPythonData() {
  try {
    console.log('Initializing database with Python-generated player data...');
    
    // Test database connection
    const { testConnection } = await import('../src/lib/db/config');
    const isConnected = await testConnection();
    if (!isConnected) {
      console.error('Failed to connect to database. Please check your database configuration.');
      process.exit(1);
    }
    
    console.log('Database connection successful!');
    
    // Create database tables
    console.log('Creating database tables...');
    await createTables();
    console.log('Database tables created successfully!');
    
    // Path to the CSV file generated by pool_elo.py
    const csvFilePath = path.join(__dirname, '..', 'data', 'pool_final_ratings.csv');
    
    // Check if CSV file exists
    if (!fs.existsSync(csvFilePath)) {
      console.log(`CSV file not found: ${csvFilePath}`);
      console.log('Generating sample data instead...');
      
      // Import and run mock data initialization
      const { populateMockData } = await import('../src/lib/db/init');
      await populateMockData();
      
      console.log('Database initialized with mock data successfully!');
      return;
    }

    // Read and parse CSV file
    console.log(`Reading player data from ${csvFilePath}...`);
    const csvData = fs.readFileSync(csvFilePath, 'utf8');
    const records: PythonRatingRow[] = await new Promise((resolve, reject) => {
      parse(csvData, {
        columns: true,
        skip_empty_lines: true,
        trim: true
      }, (err, output) => {
        if (err) reject(err);
        else resolve(output as PythonRatingRow[]);
      });
    });

    console.log(`Parsed ${records.length} players from CSV`);

    // Clear existing player data
    await query('DELETE FROM players');

    // Insert players into database
    let insertedCount = 0;
    
    // Sort players by rating (descending) to determine rankings
    const sortedRecords = [...records].sort((a, b) => 
      parseFloat(b.rating) - parseFloat(a.rating)
    );

    for (let i = 0; i < sortedRecords.length; i++) {
      const record = sortedRecords[i];
      try {
        // Generate a unique ID for the player
        const playerId = `player-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        
        // Calculate derived values
        const rating = parseFloat(record.rating);
        const matchesPlayed = parseInt(record.matches, 10);
        const provisional = matchesPlayed < 30;
        const ranking = i + 1;
        
        // For a new database, we'll assume equal wins/losses based on matches played
        // In a real implementation, this would come from actual match data
        const wins = Math.floor(matchesPlayed * 0.6); // Assume 60% win rate for demonstration
        const losses = matchesPlayed - wins;
        const winRate = matchesPlayed > 0 ? Math.round((wins / matchesPlayed) * 100) : 0;
        
        // Insert player into database
        await query(
          `INSERT INTO players (
            id, name, rating, ranking, wins, losses, win_rate, 
            avatar_url, join_date, last_played, country, breaks, 
            highest_break, description, matches_played, provisional
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)`,
          [
            playerId,
            record.player,
            rating,
            ranking,
            wins,
            losses,
            winRate,
            '', // avatar_url
            new Date(), // join_date
            new Date(), // last_played
            '', // country
            0, // breaks
            0, // highest_break
            `Player initialized from Python rating system with ${matchesPlayed} matches played.`, // description
            matchesPlayed,
            provisional
          ]
        );
        
        insertedCount++;
        console.log(`Inserted player ${record.player} with rating ${rating} and ranking ${ranking}`);
      } catch (error) {
        console.error(`Error inserting player ${record.player}:`, error);
        // Continue with other players even if one fails
      }
    }

    console.log(`Database initialized with ${insertedCount} players from Python data`);
  } catch (error) {
    console.error('Error initializing database with Python data:', error);
    process.exit(1);
  }
}

// Run the script if called directly
if (require.main === module) {
  initDatabaseWithPythonData();
}

export default initDatabaseWithPythonData;