#!/usr/bin/env tsx

// Script to run the complete player rating update workflow
// This script orchestrates the entire process of updating player ratings:
// 1. Runs the Python rating calculation script
// 2. Imports the generated CSV data into the database
// 3. Updates player rankings

import { spawn } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { query } from '../src/lib/db';

interface PythonRatingRow {
  player: string;
  rating: string;
  matches: string;
}

async function runPythonRatingCalculation(matchesFile: string, seedsFile?: string): Promise<boolean> {
  return new Promise((resolve) => {
    console.log('Starting Python rating calculation...');
    
    // Path to the Python script
    const scriptPath = path.join(__dirname, '..', '..', 'run-rating-calculation.py');
    
    // Build command arguments
    const args = ['--matches', matchesFile];
    if (seedsFile) {
      args.push('--seeds', seedsFile);
    }
    
    console.log(`Running: python3 ${scriptPath} ${args.join(' ')}`);
    
    // Spawn the Python process
    const pythonProcess = spawn('python3', [scriptPath, ...args], {
      cwd: path.join(__dirname, '..')
    });
    
    // Capture stdout
    pythonProcess.stdout.on('data', (data) => {
      process.stdout.write(`Python: ${data}`);
    });
    
    // Capture stderr
    pythonProcess.stderr.on('data', (data) => {
      process.stderr.write(`Python Error: ${data}`);
    });
    
    // Handle process completion
    pythonProcess.on('close', (code) => {
      if (code === 0) {
        console.log('Python rating calculation completed successfully');
        resolve(true);
      } else {
        console.error(`Python rating calculation failed with code ${code}`);
        resolve(false);
      }
    });
    
    // Handle process errors
    pythonProcess.on('error', (error) => {
      console.error('Failed to start Python rating calculation:', error);
      resolve(false);
    });
  });
}

async function importPlayerRatingsFromCSV(): Promise<{
  success: boolean;
  message: string;
  importedCount?: number;
  updatedCount?: number;
  error?: string;
}> {
  try {
    console.log('Importing player ratings from Python-generated CSV...');
    
    // Path to the CSV file generated by pool_elo.py
    const csvFilePath = path.join(__dirname, '..', 'data', 'pool_final_ratings.csv');
    
    // Check if CSV file exists
    if (!fs.existsSync(csvFilePath)) {
      return {
        success: false,
        message: 'CSV file not found',
        error: `File ${csvFilePath} does not exist`
      };
    }

    // Read and parse CSV file
    const csvData = fs.readFileSync(csvFilePath, 'utf8');
    const records: PythonRatingRow[] = await new Promise((resolve, reject) => {
      const { parse } = require('csv-parse');
      parse(csvData, {
        columns: true,
        skip_empty_lines: true,
        trim: true
      }, (err: Error | undefined, output: PythonRatingRow[]) => {
        if (err) reject(err);
        else resolve(output);
      });
    });

    console.log(`Parsed ${records.length} player ratings from CSV`);

    // Update player ratings in database
    let importedCount = 0;
    let updatedCount = 0;

    for (const record of records) {
      try {
        // Check if player exists in database
        const playerResult = await query(
          'SELECT id FROM players WHERE name = $1',
          [record.player]
        );

        if (playerResult.rows.length > 0) {
          // Update existing player
          const playerId = playerResult.rows[0].id;
          await query(
            `UPDATE players SET 
              rating = $1, 
              matches_played = $2,
              provisional = CASE WHEN $2 < 30 THEN true ELSE false END,
              last_played = CURRENT_TIMESTAMP
            WHERE id = $3`,
            [
              parseFloat(record.rating),
              parseInt(record.matches, 10),
              playerId
            ]
          );
          updatedCount++;
          console.log(`Updated rating for player ${record.player} (${playerId}): ${record.rating}`);
        } else {
          // Create new player
          const playerId = `player-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
          await query(
            `INSERT INTO players (
              id, name, rating, matches_played, provisional, 
              wins, losses, win_rate, ranking, join_date, last_played
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
            [
              playerId,
              record.player,
              parseFloat(record.rating),
              parseInt(record.matches, 10),
              parseInt(record.matches, 10) < 30, // provisional if < 30 matches
              0, // wins (will be calculated from matches)
              0, // losses (will be calculated from matches)
              0.0, // win_rate (will be calculated from matches)
              0, // ranking (will be calculated later)
              new Date(), // join_date
              new Date() // last_played
            ]
          );
          importedCount++;
          console.log(`Created new player ${record.player} (${playerId}) with rating: ${record.rating}`);
        }
      } catch (error) {
        console.error(`Error processing player ${record.player}:`, error);
        // Continue with other players even if one fails
      }
    }

    // Update player rankings based on new ratings
    await updatePlayerRankings();

    return {
      success: true,
      message: `Successfully imported ratings: ${importedCount} new players, ${updatedCount} updated players`,
      importedCount,
      updatedCount
    };
  } catch (error) {
    console.error('Error importing player ratings from CSV:', error);
    return {
      success: false,
      message: 'Failed to import player ratings',
      error: (error as Error).message
    };
  }
}

async function updatePlayerRankings(): Promise<void> {
  try {
    // Get all players ordered by rating (descending)
    const playersResult = await query(
      'SELECT id, rating FROM players ORDER BY rating DESC'
    );

    // Update each player's ranking
    for (let i = 0; i < playersResult.rows.length; i++) {
      const player = playersResult.rows[i];
      const ranking = i + 1;
      
      await query(
        'UPDATE players SET ranking = $1 WHERE id = $2',
        [ranking, player.id]
      );
    }

    console.log(`Updated rankings for ${playersResult.rows.length} players`);
  } catch (error) {
    console.error('Error updating player rankings:', error);
    throw error;
  }
}

async function main() {
  try {
    console.log('Starting player rating update process...');
    
    // Define file paths
    const matchesFile = path.join(__dirname, '..', 'data', 'matches.csv');
    const seedsFile = path.join(__dirname, '..', 'data', 'seeds.csv');
    
    // Check if matches file exists
    if (!fs.existsSync(matchesFile)) {
      console.error(`Matches file not found: ${matchesFile}`);
      console.error('Please create a matches.csv file in the data directory with match data');
      process.exit(1);
    }
    
    // Step 1: Run Python rating calculation
    console.log('Step 1: Running Python rating calculation...');
    const pythonSuccess = await runPythonRatingCalculation(matchesFile, fs.existsSync(seedsFile) ? seedsFile : undefined);
    
    if (!pythonSuccess) {
      console.error('Python rating calculation failed');
      process.exit(1);
    }
    
    // Step 2: Import CSV results into database
    console.log('Step 2: Importing ratings to database...');
    const importResult = await importPlayerRatingsFromCSV();
    
    if (!importResult.success) {
      console.error('Failed to import ratings to database:', importResult.error);
      process.exit(1);
    }
    
    console.log(importResult.message);
    
    console.log('Player rating update process completed successfully!');
  } catch (error) {
    console.error('Error running player rating update process:', error);
    process.exit(1);
  }
}

// Run the script if called directly
if (require.main === module) {
  main();
}

export default main;